export const data = [
  {
    name: "scroll",
    comment: "scroll does not work",
    image: "https://picsum.photos/200/300",
    link: "https://www.petra.agency/",
    status: "in progress",
    priority: 2,
  },
  {
    name: "submit",
    comment: "submit button does not work",
    image: "https://picsum.photos/200/300",
    link: "https://www.petra.agency/",
    status: "in progress",
    priority: 4,
  },
  {
    name: "link",
    comment: "the given link is broken",
    image: "https://picsum.photos/200/300",
    link: "https://www.petra.agency/",
    status: "not started",
    priority: 5,
  },
  {
    name: "scroll",
    comment: "scroll does not work",
    image: "https://picsum.photos/200/300",
    link: "https://www.petra.agency/",
    status: "in progress",
    priority: 2,
  },
  {
    name: "submit",
    comment: "submit button does not work",
    image: "https://picsum.photos/200/300",
    link: "https://www.petra.agency/",
    status: "in progress",
    priority: 4,
  },
  {
    name: "link",
    comment: "the given link is broken",
    image: "https://picsum.photos/200/300",
    link: "https://www.petra.agency/",
    status: "not started",
    priority: 5,
  },
  {
    name: "scroll",
    comment: "scroll does not work",
    image: "https://picsum.photos/200/300",
    link: "https://www.petra.agency/",
    status: "in progress",
    priority: 2,
  },
  {
    name: "submit",
    comment: "submit button does not work",
    image: "https://picsum.photos/200/300",
    link: "https://www.petra.agency/",
    status: "in progress",
    priority: 4,
  },
  {
    name: "link",
    comment: "the given link is broken",
    image: "https://picsum.photos/200/300",
    link: "https://www.petra.agency/",
    status: "not started",
    priority: 5,
  },
];
